// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "video.hxx"

// video
// 

const video::frame_sequence& video::
frame () const
{
  return this->frame_;
}

video::frame_sequence& video::
frame ()
{
  return this->frame_;
}

void video::
frame (const frame_sequence& s)
{
  this->frame_ = s;
}

const video::id_optional& video::
id () const
{
  return this->id_;
}

video::id_optional& video::
id ()
{
  return this->id_;
}

void video::
id (const id_type& x)
{
  this->id_.set (x);
}

void video::
id (const id_optional& x)
{
  this->id_ = x;
}

void video::
id (::std::auto_ptr< id_type > x)
{
  this->id_.set (x);
}

const video::location_optional& video::
location () const
{
  return this->location_;
}

video::location_optional& video::
location ()
{
  return this->location_;
}

void video::
location (const location_type& x)
{
  this->location_.set (x);
}

void video::
location (const location_optional& x)
{
  this->location_ = x;
}

void video::
location (::std::auto_ptr< location_type > x)
{
  this->location_.set (x);
}

const video::camera_optional& video::
camera () const
{
  return this->camera_;
}

video::camera_optional& video::
camera ()
{
  return this->camera_;
}

void video::
camera (const camera_type& x)
{
  this->camera_.set (x);
}

void video::
camera (const camera_optional& x)
{
  this->camera_ = x;
}


// frame
// 

const frame::object_sequence& frame::
object () const
{
  return this->object_;
}

frame::object_sequence& frame::
object ()
{
  return this->object_;
}

void frame::
object (const object_sequence& s)
{
  this->object_ = s;
}

const frame::id_optional& frame::
id () const
{
  return this->id_;
}

frame::id_optional& frame::
id ()
{
  return this->id_;
}

void frame::
id (const id_type& x)
{
  this->id_.set (x);
}

void frame::
id (const id_optional& x)
{
  this->id_ = x;
}


// object
// 

const object::fish_species_optional& object::
fish_species () const
{
  return this->fish_species_;
}

object::fish_species_optional& object::
fish_species ()
{
  return this->fish_species_;
}

void object::
fish_species (const fish_species_type& x)
{
  this->fish_species_.set (x);
}

void object::
fish_species (const fish_species_optional& x)
{
  this->fish_species_ = x;
}

void object::
fish_species (::std::auto_ptr< fish_species_type > x)
{
  this->fish_species_.set (x);
}

const object::h_optional& object::
h () const
{
  return this->h_;
}

object::h_optional& object::
h ()
{
  return this->h_;
}

void object::
h (const h_type& x)
{
  this->h_.set (x);
}

void object::
h (const h_optional& x)
{
  this->h_ = x;
}

const object::w_optional& object::
w () const
{
  return this->w_;
}

object::w_optional& object::
w ()
{
  return this->w_;
}

void object::
w (const w_type& x)
{
  this->w_.set (x);
}

void object::
w (const w_optional& x)
{
  this->w_ = x;
}

const object::x_optional& object::
x () const
{
  return this->x_;
}

object::x_optional& object::
x ()
{
  return this->x_;
}

void object::
x (const x_type& x)
{
  this->x_.set (x);
}

void object::
x (const x_optional& x)
{
  this->x_ = x;
}

const object::y_optional& object::
y () const
{
  return this->y_;
}

object::y_optional& object::
y ()
{
  return this->y_;
}

void object::
y (const y_type& x)
{
  this->y_.set (x);
}

void object::
y (const y_optional& x)
{
  this->y_ = x;
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// video
//

video::
video ()
: ::xml_schema::type (),
  frame_ (this),
  id_ (this),
  location_ (this),
  camera_ (this)
{
}

video::
video (const video& x,
       ::xml_schema::flags f,
       ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  frame_ (x.frame_, f, this),
  id_ (x.id_, f, this),
  location_ (x.location_, f, this),
  camera_ (x.camera_, f, this)
{
}

video::
video (const ::xercesc::DOMElement& e,
       ::xml_schema::flags f,
       ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  frame_ (this),
  id_ (this),
  location_ (this),
  camera_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void video::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // frame
    //
    if (n.name () == "frame" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< frame_type > r (
        frame_traits::create (i, f, this));

      this->frame_.push_back (r);
      continue;
    }

    break;
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "id" && n.namespace_ ().empty ())
    {
      this->id_.set (id_traits::create (i, f, this));
      continue;
    }

    if (n.name () == "location" && n.namespace_ ().empty ())
    {
      this->location_.set (location_traits::create (i, f, this));
      continue;
    }

    if (n.name () == "camera" && n.namespace_ ().empty ())
    {
      this->camera_.set (camera_traits::create (i, f, this));
      continue;
    }
  }
}

video* video::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class video (*this, f, c);
}

video& video::
operator= (const video& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->frame_ = x.frame_;
    this->id_ = x.id_;
    this->location_ = x.location_;
    this->camera_ = x.camera_;
  }

  return *this;
}

video::
~video ()
{
}

// frame
//

frame::
frame ()
: ::xml_schema::type (),
  object_ (this),
  id_ (this)
{
}

frame::
frame (const frame& x,
       ::xml_schema::flags f,
       ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  object_ (x.object_, f, this),
  id_ (x.id_, f, this)
{
}

frame::
frame (const ::xercesc::DOMElement& e,
       ::xml_schema::flags f,
       ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  object_ (this),
  id_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void frame::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // object
    //
    if (n.name () == "object" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< object_type > r (
        object_traits::create (i, f, this));

      this->object_.push_back (r);
      continue;
    }

    break;
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "id" && n.namespace_ ().empty ())
    {
      this->id_.set (id_traits::create (i, f, this));
      continue;
    }
  }
}

frame* frame::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class frame (*this, f, c);
}

frame& frame::
operator= (const frame& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->object_ = x.object_;
    this->id_ = x.id_;
  }

  return *this;
}

frame::
~frame ()
{
}

// object
//

object::
object ()
: ::xml_schema::type (),
  fish_species_ (this),
  h_ (this),
  w_ (this),
  x_ (this),
  y_ (this)
{
}

object::
object (const object& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  fish_species_ (x.fish_species_, f, this),
  h_ (x.h_, f, this),
  w_ (x.w_, f, this),
  x_ (x.x_, f, this),
  y_ (x.y_, f, this)
{
}

object::
object (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  fish_species_ (this),
  h_ (this),
  w_ (this),
  x_ (this),
  y_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void object::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "fish_species" && n.namespace_ ().empty ())
    {
      this->fish_species_.set (fish_species_traits::create (i, f, this));
      continue;
    }

    if (n.name () == "h" && n.namespace_ ().empty ())
    {
      this->h_.set (h_traits::create (i, f, this));
      continue;
    }

    if (n.name () == "w" && n.namespace_ ().empty ())
    {
      this->w_.set (w_traits::create (i, f, this));
      continue;
    }

    if (n.name () == "x" && n.namespace_ ().empty ())
    {
      this->x_.set (x_traits::create (i, f, this));
      continue;
    }

    if (n.name () == "y" && n.namespace_ ().empty ())
    {
      this->y_.set (y_traits::create (i, f, this));
      continue;
    }
  }
}

object* object::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class object (*this, f, c);
}

object& object::
operator= (const object& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->fish_species_ = x.fish_species_;
    this->h_ = x.h_;
    this->w_ = x.w_;
    this->x_ = x.x_;
    this->y_ = x.y_;
  }

  return *this;
}

object::
~object ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::auto_ptr< ::video >
video_ (const ::std::string& u,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::auto_ptr< ::video > (
    ::video_ (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::video >
video_ (const ::std::string& u,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::video > (
    ::video_ (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::video >
video_ (const ::std::string& u,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::video > (
    ::video_ (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::video >
video_ (::std::istream& is,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::video_ (isrc, f, p);
}

::std::auto_ptr< ::video >
video_ (::std::istream& is,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::video_ (isrc, h, f, p);
}

::std::auto_ptr< ::video >
video_ (::std::istream& is,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::video_ (isrc, h, f, p);
}

::std::auto_ptr< ::video >
video_ (::std::istream& is,
        const ::std::string& sid,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::video_ (isrc, f, p);
}

::std::auto_ptr< ::video >
video_ (::std::istream& is,
        const ::std::string& sid,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::video_ (isrc, h, f, p);
}

::std::auto_ptr< ::video >
video_ (::std::istream& is,
        const ::std::string& sid,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::video_ (isrc, h, f, p);
}

::std::auto_ptr< ::video >
video_ (::xercesc::InputSource& i,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::auto_ptr< ::video > (
    ::video_ (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::video >
video_ (::xercesc::InputSource& i,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::video > (
    ::video_ (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::video >
video_ (::xercesc::InputSource& i,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::auto_ptr< ::video > (
    ::video_ (
      d, f | ::xml_schema::flags::own_dom, p));
}

::std::auto_ptr< ::video >
video_ (const ::xercesc::DOMDocument& doc,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::auto_ptr< ::video > (
      ::video_ (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "video" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::video > r (
      ::xsd::cxx::tree::traits< ::video, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "video",
    "");
}

::std::auto_ptr< ::video >
video_ (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d,
        ::xml_schema::flags f,
        const ::xml_schema::properties&)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "video" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::video > r (
      ::xsd::cxx::tree::traits< ::video, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "video",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

void
video_ (::std::ostream& o,
        const ::video& s,
        const ::xml_schema::namespace_infomap& m,
        const ::std::string& e,
        ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::video_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
video_ (::std::ostream& o,
        const ::video& s,
        ::xml_schema::error_handler& h,
        const ::xml_schema::namespace_infomap& m,
        const ::std::string& e,
        ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::video_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
video_ (::std::ostream& o,
        const ::video& s,
        ::xercesc::DOMErrorHandler& h,
        const ::xml_schema::namespace_infomap& m,
        const ::std::string& e,
        ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::video_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
video_ (::xercesc::XMLFormatTarget& t,
        const ::video& s,
        const ::xml_schema::namespace_infomap& m,
        const ::std::string& e,
        ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::video_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
video_ (::xercesc::XMLFormatTarget& t,
        const ::video& s,
        ::xml_schema::error_handler& h,
        const ::xml_schema::namespace_infomap& m,
        const ::std::string& e,
        ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::video_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
video_ (::xercesc::XMLFormatTarget& t,
        const ::video& s,
        ::xercesc::DOMErrorHandler& h,
        const ::xml_schema::namespace_infomap& m,
        const ::std::string& e,
        ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::video_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
video_ (::xercesc::DOMDocument& d,
        const ::video& s,
        ::xml_schema::flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "video" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "video",
      "");
  }
}

::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
video_ (const ::video& s,
        const ::xml_schema::namespace_infomap& m,
        ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "video",
      "",
      m, f));

  ::video_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const video& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // frame
  //
  for (video::frame_const_iterator
       b (i.frame ().begin ()), n (i.frame ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "frame",
        e));

    s << *b;
  }

  // id
  //
  if (i.id ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "id",
        e));

    a << *i.id ();
  }

  // location
  //
  if (i.location ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "location",
        e));

    a << *i.location ();
  }

  // camera
  //
  if (i.camera ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "camera",
        e));

    a << *i.camera ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const frame& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // object
  //
  for (frame::object_const_iterator
       b (i.object ().begin ()), n (i.object ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "object",
        e));

    s << *b;
  }

  // id
  //
  if (i.id ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "id",
        e));

    a << *i.id ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const object& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // fish_species
  //
  if (i.fish_species ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "fish_species",
        e));

    a << *i.fish_species ();
  }

  // h
  //
  if (i.h ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "h",
        e));

    a << *i.h ();
  }

  // w
  //
  if (i.w ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "w",
        e));

    a << *i.w ();
  }

  // x
  //
  if (i.x ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "x",
        e));

    a << *i.x ();
  }

  // y
  //
  if (i.y ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "y",
        e));

    a << *i.y ();
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

