@echo off

set BOOST_EXEC_DIR=%BOOST_DIR%
set OPENCV_EXEC_DIR=%OPENCV_DIR%\vc10\bin
set XERCES_EXEC_DIR=%XERCES_DIR%\bin
set XALAN_EXEC_DIR=%XALAN_DIR%\bin
set XQILLA_EXEC_DIR=%XQILLA_DIR%\%XQILLA_CONFIGURATION%
set XSD_EXEC_DIR=%XSD_DIR%\bin

set EXEC_DIR_PATH=%BOOST_EXEC_DIR%;%OPENCV_EXEC_DIR%;%XERCES_EXEC_DIR%;%XALAN_EXEC_DIR%;%XQILLA_EXEC_DIR%;%XSD_EXEC_DIR%
