@echo off

REM -- Per platform ENV VARs
REM -- x64
set BOOST_DIR=%BOOST_X64_DIR%
set OPENCV_DIR=%OPENCV_X64_DIR%
set XERCES_DIR=%XERCES_X64_DIR%
set XALAN_DIR=%XALAN_X64_DIR%

REM -- x64 Release
set XQILLA_CONFIGURATION=Release
set XQILLA_DIR=%XQILLA_X64_DIR%
set XQILLA_EXEC_DIR=%XQILLA_DIR%\%XQILLA_CONFIGURATION%
